### ISSUE TITLE
Questions about nameplates icon

### ISSUE THREAD

**Issue by 248bdh** [widxwer/Questie#10]
Hello!
I'd like to report a bug here.
The nameplates icon will only be displayed on some monsters.
![a](https://github.com/widxwer/Questie/assets/78687557/5165e78f-1258-4082-8425-8440a4f02f40)
As shown in the figure.
The nameplates icon is only displayed on the two monsters on the right, while nothing is displayed above the two monsters on the left.
In addition, I found that if I rotated the angle of view, such as turning the angle 90 degrees to the left and then turning the angle of view back, the display of the nameplates icon would change again.
Some monsters' nameplates icon will disappear, while others will display nameplates icon.

**Comment by widxwer** [comment]
@248bdh What is the name of the nameplate addon that you are using? Have you tried disabling it?

**Comment by 248bdh** [comment]
> @248bdh What is the name of the nameplate addon that you are using? Have you tried disabling it?

The nameplate plugin I am using is KuiNameplates-WoTLK.
Download link:
https://github.com/bkader/KuiNameplates-WoTLK
After checking, I found that this problem is indeed related to plug-ins.
When the plugin is disabled, everything appears fine.
Thank you for your help!

**Comment by widxwer** [comment]
@248bdh Fixed in [0d17675](https://github.com/widxwer/Questie/commit/0d1767542593bd73403651f072812028b8cd6fa8).
