### ISSUE TITLE
SelectQuestLogEntry error

### ISSUE THREAD

**Issue by Crumdidlyumshis** [widxwer/Questie#11]
Just want to say first, great work backporting this! Thank you so much! It has been I don't know how long since I've yearned for this type of addon to be ported to 3.3.5. I was going to do it myself but never got around to it.

## Bug description

Somehow I have a quest that I believe I completed but didn't update for some reason. When I click on the tracker title, it threw the error. All the other quests seem to be in my questlog. 
"Report to Lord Devrestrasz": https://www.wowhead.com/wotlk/npc=27575/lord-devrestrasz

## Screenshots

![Screenshot 2024-06-12 213605](https://github.com/widxwer/Questie/assets/7307335/22554ffc-f2c7-4c9c-a5e3-53093287c208)
![Screenshot 2024-06-12 213837](https://github.com/widxwer/Questie/assets/7307335/8b4fa2ce-9a26-49a5-b354-cd94ceb7405b)

## Questie & WoW version

v9.5.1

**Comment by Crumdidlyumshis** [comment]
After a quick /rl the quest disappeared out of the tracker. Something didn't update correctly somewhere.

**Comment by widxwer** [comment]
@Crumdidlyumshis Thank you for the support! Apparently, that quest was [renamed](https://www.wowhead.com/news/references-to-alex-afrasiabi-removed-in-world-of-warcraft-323588) in Classic, but private servers are still using the original name.
![image](https://github.com/widxwer/Questie/assets/114254296/d644e04d-3dc3-492a-9637-dce83ce85a2d)

**Comment by Crumdidlyumshis** [comment]
That makes sense. I had no idea about that director. Now I see why 😭

**Comment by widxwer** [comment]
Fixed in [0d17675](https://github.com/widxwer/Questie/commit/0d1767542593bd73403651f072812028b8cd6fa8). Database recompilation is required for the changes to take effect.
