### ISSUE TITLE
Dailies

### ISSUE THREAD

**Issue by disruption01** [widxwer/Questie#14]
It seems that the fishing/cooking dailies of shattrath are not showing up in questie.

**Comment by Kahuma1** [comment]
Just checked, if you mean on the worldmap then no, if you accept them they are shown in Questie Tracker.

**Comment by disruption01** [comment]
> Just checked, if you mean on the worldmap then no, if you accept them they are shown in Questie Tracker.

yeah sorry I meant on the world map

**Comment by widxwer** [comment]
Could you provide the name or ID of the missing daily quests?

**Comment by widxwer** [comment]
![image](https://github.com/widxwer/Questie/assets/114254296/b186f98e-2e49-4fde-aa68-dff238995d91)
Are those the quests that are not showing up?

**Comment by disruption01** [comment]
Yes

**Comment by widxwer** [comment]
Can you show me your Character Skills tab?

**Comment by disruption01** [comment]
> Can you show me your Character Skills tab?

![image](https://github.com/widxwer/Questie/assets/44980177/daa9285a-71a2-4b3d-a1d8-9368ceaddee6)

**Comment by widxwer** [comment]
On a fresh level 70 character with 300 cooking, those quests are visible on the map, minimap, and tooltip.
![image](https://github.com/widxwer/Questie/assets/114254296/6e3525c8-3641-4d9c-a218-1d085d520eda)

**Comment by disruption01** [comment]
![image](https://github.com/widxwer/Questie/assets/44980177/2bc8e449-d506-4a30-95e1-43ad702b3a08)

**Comment by disruption01** [comment]
![image](https://github.com/widxwer/Questie/assets/44980177/e3988fe9-0644-40ef-b51d-d7468932aa70)

**Comment by disruption01** [comment]
do you think it can be a server issue?

![image](https://github.com/widxwer/Questie/assets/44980177/3f0f9dc2-67f5-4a8a-b185-0c4a9b820458)

shows up like this.

**Comment by disruption01** [comment]
![image](https://github.com/widxwer/Questie/assets/44980177/ca209af9-b5fa-4a40-83b1-2b2b8dbbd01c)

**Comment by widxwer** [comment]
> do you think it can be a server issue?

As far as I know, it should work the same no matter the server.

**Comment by Crumdidlyumshis** [comment]
This may also be related. I have a quest I finished that's a Daily and it too does not show. If I click the "Show Quest Objectives" for the default wow icons, it shows up where it should be, but Questie doesn't.

![image](https://github.com/widxwer/Questie/assets/7307335/c036899d-fab6-44b0-a725-01b8e09f40f6)
![image](https://github.com/widxwer/Questie/assets/7307335/e672230c-b67f-41eb-bb58-c0ed6b9bb710)
![image](https://github.com/widxwer/Questie/assets/7307335/fa2babfe-8d46-4f80-9129-f9e1a685bd0c)

**Comment by widxwer** [comment]
@disruption01 Could you check the "Doable" status in the Questie Journey for any of the level 70 cooking quests, such as [Manalicious](https://www.wowhead.com/wotlk/quest=11380)? (My Journey -> Advanced Search tab -> Search by ID -> 11380)
![image](https://github.com/widxwer/Questie/assets/114254296/8f6a9dcb-b7dd-4ce8-a367-1c3d3598baf4)

**Comment by widxwer** [comment]
@Crumdidlyumshis Could you also check the "Doable" status in the Questie Journey for the quest ID 12038

**Comment by Kahuma1** [comment]
@widxwer 
Quest  11380
![grafik](https://github.com/widxwer/Questie/assets/92261432/92182e83-a7a0-43ce-a401-c08853aa5228)
Is doable for me but under NPCs its Jin'do the Hexxer not Rokk.
Quest 12038 also doable and iam  eligible for the quest.

**Comment by widxwer** [comment]
@Kahuma1 Is the quest icon for 12038 shown on your map?

**Comment by Kahuma1** [comment]
Yes is shown on Map

**Comment by Crumdidlyumshis** [comment]
@widxwer 
![image](https://github.com/widxwer/Questie/assets/7307335/5defcffd-63b1-49e6-ad10-1c82b5acbd90)
![image](https://github.com/widxwer/Questie/assets/7307335/6d4f956f-1eb5-4f31-b5dd-30f022fb9c96)

**Comment by Crumdidlyumshis** [comment]
![image](https://github.com/widxwer/Questie/assets/7307335/744548bf-3b1d-4a75-97d1-442dc3f9c53b)

**Comment by widxwer** [comment]
Should be fixed in [fc1e781](https://github.com/widxwer/Questie/commit/fc1e781285c8bdc06b83e27a1989cc89b585568f)

**Comment by Crumdidlyumshis** [comment]
![image](https://github.com/widxwer/Questie/assets/7307335/f5b4bdda-3502-44ce-8492-6a894765a532)
Confirmed, its fixed! <3 Thank you

**Comment by widxwer** [comment]
With the [commit 73c82e9](https://github.com/widxwer/Questie/commit/73c82e96ab679dba45072f936ebf9bbd81613d34), Questie should handle the reset times of daily and weekly quests. In Classic, this is managed internally by the server, but on private servers, the implementation differs from server to server, which caused the issue in the first place. The daily reset time can be fetched from the server, but the weekly reset time needs to be set manually by the user (Options -> Advanced -> 3.3.5 Compatibility Settings -> Weekly Reset Day).

**Comment by disruption01** [comment]
> With the [commit 73c82e9](https://github.com/widxwer/Questie/commit/73c82e96ab679dba45072f936ebf9bbd81613d34), Questie should handle the reset times of daily and weekly quests. In Classic, this is managed internally by the server, but on private servers, the implementation differs from server to server, which caused the issue in the first place. The daily reset time can be fetched from the server, but the weekly reset time needs to be set manually by the user (Options -> Advanced -> 3.3.5 Compatibility Settings -> Weekly Reset Day).

thank you for the awesome work mate
