### ISSUE TITLE
[Quest] Burning to Help

### ISSUE THREAD

**Issue by Crumdidlyumshis** [widxwer/Questie#16]
## Bug description

Quest [Burning to Help] appears on minimap and map as if its available. I am level 76, shows 77.

Quest ID# 12683

## Screenshots

![image](https://github.com/widxwer/Questie/assets/7307335/23d72ec4-c05b-44fa-a182-c177cdb90b4d)

![image](https://github.com/widxwer/Questie/assets/7307335/d5abd00c-6de7-4441-b37a-0e2cc271e2ce)

## Questie & WoW version

v9.5.1

**Comment by Crumdidlyumshis** [comment]
Then again... maybe this is Warmane bug? 
![image](https://github.com/widxwer/Questie/assets/7307335/b59c7209-4cdc-4fa7-942f-5226dc4354b0)

**Comment by widxwer** [comment]
@Crumdidlyumshis According to WowHead, the minimum level required to receive this quest is 76, while the level displayed in the tooltip is the level of the quest itself. It seems like this is a server-specific issue and the quest should be available at 76.
![image](https://github.com/user-attachments/assets/01af5f06-78c8-4652-8229-389455735e92)
