### ISSUE TITLE
Quests by Zone showing quests completed even if they're not

### ISSUE THREAD

**Issue by andovcr** [widxwer/Questie#18]
/questie
select My Journey in the upper right
Quests by Zone tab

Here I see all quests for any given zone being shown as Completed, even when they have not been.  Would it be possible to fix this, so we could use this tab to see which quests are left to do in a given zone?

Here's a screenshot, where you can see the quest giver has at least 2 quests still to give, but they are shown as fully complete for this zone:
<img width="906" alt="image" src="https://github.com/user-attachments/assets/ff8af278-3a7e-4740-9541-1aa59fb7b5d4">

**Comment by widxwer** [comment]
@andovcr Could you download the latest version of Questie, perform a clean install (removing ...\WTF\Account[ACCOUNT_NAME]\SavedVariables\Questie-335.lua), and confirm if it’s still bugged? I remember fixing this issue a long time ago.

**Comment by andovcr** [comment]
Fixed!

I had downloaded the latest version this past week, but didn't delete the SavedVariables data - thank you!
