### ISSUE TITLE
Icons problem

### ISSUE THREAD

**Issue by adrisalv** [widxwer/Questie#19]
Icons disappear when I zoom in in the map but if I zoom out icons appear (not on the place they should be though)
![image](https://github.com/user-attachments/assets/842869ca-7073-4ce9-983a-009ed42e01df)
![image](https://github.com/user-attachments/assets/c70cdb45-a3ff-4a2b-ad57-ec19ae206079)

**Comment by adrisalv** [comment]
I have to add that with other account, with the same addons and same weak auras activated works perfectly, I've disabled major addons like ElvUI and WA but keeps happening

**Comment by adrisalv** [comment]
When I try to enable the tracker this LUA error pops 
![image](https://github.com/user-attachments/assets/b5c75304-168c-4792-972b-5f02b87807ff)

**Comment by adrisalv** [comment]
I redownloaded, I copied saved variables files from the good account to the bad account but nothing changes

**Comment by adrisalv** [comment]
I figured out what is it... It's a bug related with being inside the draenei's starter zone...
![image](https://github.com/user-attachments/assets/7dd869af-335e-4f96-8cf8-1278df15e1b0)
It works fine on the next map

**Comment by Crumdidlyumshis** [comment]
Yeah this same thing happening to me in Shadowglen.

This issue is not resolved. Should reopen

**Comment by Crumdidlyumshis** [comment]
![image](https://github.com/user-attachments/assets/070e2392-bcf0-49be-9e39-051162e728e5)
![image](https://github.com/user-attachments/assets/31d5a368-fd3a-418f-8442-467320f2cd15)

**Comment by Crumdidlyumshis** [comment]
Tried a new character without any addons enabled except questie, logged into a troll starting zone and it did the same thing as above. For whatever reason will not show the quests in the starting zone unless zoomed out

**Comment by widxwer** [comment]
@Crumdidlyumshis I’m unable to reproduce the issue. Could you provide more details?

**Comment by widxwer** [comment]
Since when do Shadowglen and Ammen Vale have their own world maps in 3.3.5? You're definitely using world map client patches, which Questie does not support.

**Comment by Crumdidlyumshis** [comment]
Haha I believe your right and never thought about that before. The maps are just so seemless.

**Comment by Crumdidlyumshis** [comment]
![image](https://github.com/user-attachments/assets/7401cdee-b5a1-48df-a197-dc71806cad36)
