### ISSUE TITLE
kill / collect quests tracker not showing progress

### ISSUE THREAD

**Issue by endershan** [widxwer/Questie#2]
Hi! I find that when I am doing kill / collect kind of quests, the tracker only shows 0/1 when the quest is unfinished, instead of something like 12/15. This is also true for the tooltip tracker. You can see them in the following pics.
![6a4f37eddab63ebfa2319dbbe18e74b](https://github.com/widxwer/Questie/assets/68373127/0549ecf1-019e-4636-b9b1-fb07a8bfb7f2)
![e3a118d688f64d87107c23a6a190454](https://github.com/widxwer/Questie/assets/68373127/c234cf27-0660-49ed-a8ea-1f166ebbe899)
BTW, thank you for your great work! It already improved my questing experience in 3.3.5 by a big deal!

**Comment by widxwer** [comment]
Fixed in [c84e91a](https://github.com/widxwer/Questie/commit/c84e91a571ee4640b9df69b2308a6805704790a2)
Thanks to @endershan for the provided solution
