### ISSUE TITLE
Multiple quests not showing on map in Zul'Drak

### ISSUE THREAD

**Issue by Crumdidlyumshis** [widxwer/Questie#22]
## Description

The following quests just don't appear on the map. I am sure there is more to come, but for now this is what I am finding.

## Wowhead link

12562: The Drakkari Do Not Need Water Elementals
https://www.wowhead.com/wotlk/quest=12562/the-drakkari-do-not-need-water-elementals

12503: Defend the Stand
https://www.wowhead.com/wotlk/quest=12503/defend-the-stand

12740: Parachutes for the Argent Crusade
https://www.wowhead.com/wotlk/quest=12740/parachutes-for-the-argent-crusade

12796: The Magical Kingdom of Dalaran
https://www.wowhead.com/wotlk/quest=12796/the-magical-kingdom-of-dalaran

12565: The Blessing of Zim`Abwa
https://www.wowhead.com/wotlk/quest=12565/the-blessing-of-zimabwa

12527: Gluttonous Lurkers
https://www.wowhead.com/wotlk/quest=12527/gluttonous-lurkers

## Screenshots

![image](https://github.com/user-attachments/assets/cc6e549d-b4a7-4626-b01d-ca85b9808f54)
![image](https://github.com/user-attachments/assets/930beaff-884a-40d4-8021-d78356ed7cfc)

## Questie & WoW version

![image](https://github.com/user-attachments/assets/0b518f1e-b955-4c0d-8859-8e7f38391b00)

**Comment by widxwer** [comment]
@Crumdidlyumshis 12562 and 12527 require a pre-quest. The rest are visible for me at the appropriate level. You can check the status of any quest in "Journey" by looking at the "Doable" line.

**Comment by Crumdidlyumshis** [comment]
Hmm, its just weird, im lvl 76, and on the minimap the quests show up just fine. On the map through questie they do not show up at all. I checked the doable and the two mentioned say they are "Incomplete pre-quest".
![image](https://github.com/user-attachments/assets/fb35fa93-ea4c-48f3-8b3c-be8c2ebb0f65)

I get that, but if the quests are available on the map, meaning I can see them showing on the minimap and I am able to do them, should they not be showing on the map as well?

I tried recompiling DB and disabling all addons except questie, idk. Maybe my logic is wrong.

As you can see, other quests on the map show up like in the far top right corner.

![image](https://github.com/user-attachments/assets/24602c8d-2e34-47d8-b101-db5f8325510e)

These quests should be showing on the map right here:
![image](https://github.com/user-attachments/assets/eff31b33-87b4-4039-9def-5537a21bb9e4)
![image](https://github.com/user-attachments/assets/4e0638aa-3075-4098-ab48-a7754c0f8865)

**Comment by widxwer** [comment]
You can see them on the minimap as available, because private servers still have inaccurate (non-Blizzlike) quest data in their databases, assuming the Questie database is accurate/Blizzlike.

**Comment by Crumdidlyumshis** [comment]
What server are you testing on out of curiosity?

**Comment by widxwer** [comment]
I am running a self-hosted TrinityCore server.

**Comment by widxwer** [comment]
What is the "Doable" status of 12503, 12740, 12796, 12565?

**Comment by Crumdidlyumshis** [comment]
> What is the "Doable" status of 12503, 12740, 12796, 12565?

![image](https://github.com/user-attachments/assets/e2d95b38-18d3-4fc3-baa4-c1809d8f1823)
![image](https://github.com/user-attachments/assets/1b0624d8-8231-4f81-bb4e-c916c060f52f)
![image](https://github.com/user-attachments/assets/1ff6f4c6-8fca-48eb-b009-83932ca40106)
![image](https://github.com/user-attachments/assets/f767b099-e058-46c1-9e73-bb00c11fced9)

**Comment by widxwer** [comment]
I just checked again, and the quests are visible for me with a fresh level 76 character. You might want to try a clean install ( removing "...\WTF\Account[ACCOUNT_NAME]\SavedVariables\Questie-335.lua").

**Comment by Crumdidlyumshis** [comment]
Okay, so I got around to playing again. I deleted what you said and yes it worked (somewhat). More quests showed up on the map, and of the ones listed, three of the six listed (3/6) showed up.

![image](https://github.com/user-attachments/assets/c97143bc-a712-4202-976a-966cbd39e2c7)
![image](https://github.com/user-attachments/assets/f8e82304-8a70-40b9-afed-cae3befc7e94)
![image](https://github.com/user-attachments/assets/e0408ac4-49fc-40b8-a6ab-7741698ea87e)

**Comment by Marotheit** [comment]
![image](https://private-user-images.githubusercontent.com/7307335/374020308-930beaff-884a-40d4-8021-d78356ed7cfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1MzYyNTAsIm5iZiI6MTczMDUzNTk1MCwicGF0aCI6Ii83MzA3MzM1LzM3NDAyMDMwOC05MzBiZWFmZi04ODRhLTQwZDQtODAyMS1kNzgzNTZlZDdjZmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDJUMDgyNTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjE4NzQ2NDY5ZGUyODkyYjE1ZmYyNjVmMGVlNmY4YjlkZTMwZmQ0NjlmZGY2MDA4Y2RhODRlMTY2NGYwYmRlMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.3JQICfaNn7EfwSOcMh3zBvFa3bN6xMGd_u_hEbKWZu8)

I'm so sorry to detract from the conversation, but I have to ask where I can find these ridiculously high resolution maps?

**Comment by Crumdidlyumshis** [comment]
> ![image](https://private-user-images.githubusercontent.com/7307335/374020308-930beaff-884a-40d4-8021-d78356ed7cfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1MzYyNTAsIm5iZiI6MTczMDUzNTk1MCwicGF0aCI6Ii83MzA3MzM1LzM3NDAyMDMwOC05MzBiZWFmZi04ODRhLTQwZDQtODAyMS1kNzgzNTZlZDdjZmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDJUMDgyNTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjE4NzQ2NDY5ZGUyODkyYjE1ZmYyNjVmMGVlNmY4YjlkZTMwZmQ0NjlmZGY2MDA4Y2RhODRlMTY2NGYwYmRlMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.3JQICfaNn7EfwSOcMh3zBvFa3bN6xMGd_u_hEbKWZu8)
> 
> I'm so sorry to detract from the conversation, but I have to ask where I can find these ridiculously high resolution maps?

https://forum.warmane.com/showthread.php?t=456071
