### ISSUE TITLE
Question: How can I add a custom quest to work with Questie?

### ISSUE THREAD

**Issue by Aldori15** [widxwer/Questie#23]
## Question

Hello, I am running an Azerthcore 3.3.5 server and using the latest version of Questie.  My server has some custom made quests that don't exist in Questie (and I wouldn't expect them to since they are custom made).

Can you walk me through how I can go about adding the quest to work with Questie for my server?  Here's two of them for reference:
https://wow.tanados.com/database/?quest=41
https://wow.tanados.com/database/?quest=42

Accepting the quest I get this message (expected of course since it doesn't exist in Questie).

![image](https://github.com/user-attachments/assets/6a00a38b-3837-4733-92a1-39351c773ac1)

Any help would be greatly appreciated!  :)

**Comment by Aldori15** [comment]
[Questie Quests.txt](https://github.com/user-attachments/files/17578687/Questie.Quests.txt)

I also exported both database rows so you can see the full info.

**Comment by widxwer** [comment]
Hi, the easiest and cleanest way is to create a separate addon with `## Dependencies: Questie-335` in the .toc file, then add your custom quest data to a .lua file similar to [this example](https://pastebin.com/pQhUNXsk). You can refer to `itemDB.lua`, `npcDB.lua`, `objectDB.lua`, and `questDB.lua` in `../Questie/Database/` for descriptions of the dbKeys.

**Comment by Aldori15** [comment]
Hi, thank you for the reply.  Just to make sure I'm looking at the correct spot for the quest keys.  It's this here, correct?

![image](https://github.com/user-attachments/assets/f12f8201-d118-4de6-af65-080ef342389a)

Also, do I need to set all of the quest keys for it to work?

**Comment by widxwer** [comment]
@Aldori15 yes, this is it. I don’t think all quest keys are necessary, it depends on the quest. Check out https://github.com/Questie/Questie/wiki/Corrections for more info.

**Comment by Aldori15** [comment]
@widxwer Sorry to bother.  I still can't seem to get it to work.  I made the separate addon with the toc file and separate lua file.  The quest still shows missing when I try to accept it.  It also doesn't appear on the map when i hover over the icon for the questgiver.  It shows the other breadcrumb quests though.

![image](https://github.com/user-attachments/assets/b67a30cc-e255-4be5-a489-2f19847871b9)

![image](https://github.com/user-attachments/assets/f4d34d7c-7ed2-48a0-9715-60ed3c58812f)

**Comment by Aldori15** [comment]
![image](https://github.com/user-attachments/assets/46f0e933-98f9-4756-9ff6-9e49c94452a3)

Ah okay I did not see this in the Corrections page so I will try this step tomorrow.

Apart from recompiling the database, is there anything else you can think of that I may be missing?

**Comment by widxwer** [comment]
@Aldori15  You are missing the actual [quest objectives](https://github.com/Questie/Questie/wiki/Quest-objective-types): `[questKeys.objectives] = {{{900003}}}`. Also, since this NPC is custom, you need to add it to `npcData`.

**Comment by Aldori15** [comment]
@widxwer Ah okay.  Thank you, i'll give it a shot tonight.  I did think about the npcData but I thought that was more-so referring to the quest giver/ender and not the actual objective NPC.

**Comment by Aldori15** [comment]
@widxwer It works.  Thank you so much for the help!

**Comment by Aldori15** [comment]
@widxwer Hello, was hoping you could answer one more question for me.  I have a custom category in QuestSort.dbc that uses ID 377 called "Scourge Invasion".

I updated `QuestieDB.sortKeys` in Constants.lua to add a SCOURAGE_INVASION = -377 as shown here:
![image](https://github.com/user-attachments/assets/d08f432e-368a-4583-ae04-5db0db304baa)

Then I set a reference to it in my custom script:
![image](https://github.com/user-attachments/assets/090266c4-f1f1-4d73-8a83-bdd9dcae418f)

Then you can see I am setting `questKeys.zoneOrSort = sortKeys.SCOURAGE_INVASION`:
![image](https://github.com/user-attachments/assets/864b3366-d012-4ca4-83a8-648597fc0fae)

But in game it's showing Unknown Category:
![image](https://github.com/user-attachments/assets/33461582-c0be-4ae7-b09c-ad9dcb00ab51)


I even tried to hardcode the -377 by setting `questKeys.zoneOrSort = -377` but the same results when recompiling the database.

According to the questKeys, it says a negative value will use QuestSort.dbc.  Do you know if I'm missing a step somewhere?
![image](https://github.com/user-attachments/assets/f4540507-a34d-41e6-87e3-559f106da21d)

The main quest log it works fine (outside of Questie), so it's properly set up in QuestSort.dbc, but I just can't figure out how to update the Questie objective tracker.
![image](https://github.com/user-attachments/assets/07b4e379-f763-4131-914c-a885fa2e8983)

**Comment by Aldori15** [comment]
Sorry, should have looked a little further before asking.  I was able to resolve it by also adding it `lookupQuestCategories.lua` and `lookupZones.lua`

![image](https://github.com/user-attachments/assets/3d573e14-bef3-4f7f-b797-24d408749528)
