### ISSUE TITLE
unable to link quest if ChatStrictLinkChecking.Severity set to 1

### ISSUE THREAD

**Issue by Aokromes** [widxwer/Questie#24]
Hi, i have a server with the config of ChatStrictLinkChecking.Severity set to 1
when someone tries to link a quest, the link is blocked because questie adds quest id linkin
IE

 [[80] La purificación de Quel'Delar (24594)]
if i copy and paste the text before press enter the quest is show

## Questie & WoW version
QuestIE 9.5.1 for wow 3.3.5a

**Comment by widxwer** [comment]
The only solution I can think of is to allow the disabling of Questie quest links through the Options.

**Comment by Deiwulf** [comment]
Yeah, just tracked the same issue to this addon after messages vanishing on any warmane's channel with a quest link included. 
Disabling it would be nice.

**Comment by boegi1** [comment]
Agreed. Would be great to have such an option.

**Comment by CraftedRO** [comment]
confirm

**Comment by widxwer** [comment]
Questie quest links are disabled by default with the [3f8e72f](https://github.com/widxwer/Questie/commit/3f8e72fdf11ca7ae07e4b629b41be632382227b7) commit and can be reenabled in the Options.

**Comment by boegi1** [comment]
Works like a charm. Thanks a lot @widxwer !
