### ISSUE TITLE
nameplates icon options

### ISSUE THREAD

**Issue by azmahski** [widxwer/Questie#3]
## Question

how can we use nameplate icon ooptioons , its disabled on the addon , thanks
![WoWScrnShot_051424_220411](https://github.com/widxwer/Questie/assets/35508656/fa38bbcd-516e-4368-b797-da237790c29b)

**Comment by widxwer** [comment]
Nameplate functionality has not been implemented yet.

**Comment by widxwer** [comment]
@azmahski implemented it in [816bcd4](https://github.com/widxwer/Questie/commit/816bcd4a41a436afdf1156b399a9da47f253b54b). Nameplate options are now active.

**Comment by azmahski** [comment]
that work perfectly you are legend @widxwer
