### ISSUE TITLE
MinimapButtonFrame compat

### ISSUE THREAD

**Issue by rootwalla** [widxwer/Questie#4]
version: 9.5.1
Wotlk 3.3.5a

It appears Questie reacts badly if MinimapButtonFrame is installed (it somehow collects all your minimap pins)
https://felbite.com/addon/3774-minimapbuttonframe/

**Comment by 248bdh** [comment]
Why not upload a picture?
Even if an icon is collected, it shouldn't have much of an impact.

**Comment by widxwer** [comment]
The addon you linked doesn't even work out of the box... Anyway, adding QuestieFrame to the addon exceptions should fix your issue. Also you can download [https://www.curseforge.com/wow/addons/mbb/download/462180](MBB), which works with Questie without any additional configuration.
![image](https://github.com/widxwer/Questie/assets/114254296/5092e5ee-87fc-4b79-a231-4ded1b525519)
![image](https://github.com/widxwer/Questie/assets/114254296/25a8252e-ed5d-464a-ad9d-dc4accdcc78c)

**Comment by rootwalla** [comment]
I was not aware of that MBB version, thank you.

**Comment by widxwer** [comment]
@rootwalla "QuestieFrame" is now automatically added to the MinimapButtonFrame exceptions list in [0daf5d0](https://github.com/widxwer/Questie/commit/0daf5d02e2a7723a6f5fdbdd61f83f73984e0eac)
