### ISSUE TITLE
Lua Errors for Nameplates Icon

### ISSUE THREAD

**Issue by Kahuma1** [widxwer/Questie#5]
## Bug description

I Get the following LUA Error for every NPC tracked by Questie with Namplates Icons activated.
Activate Nameplates Icon ,kill mobs with icon.
2x Questie-335-9.5.1\Modules\QuestieNameplate.lua:210: <unnamed>:SetParent(): Couldn't find region named 'Creature-0-4170-0-41-5615-00000F4B37'
Questie-335-9.5.1\Modules\QuestieNameplate.lua:210: in function `GetFrame'
Questie-335-9.5.1\Modules\QuestieNameplate.lua:57: in function <...face\AddOns\Questie-335\Modules\QuestieNameplate.lua:27>
<string>:"safecall Dispatcher[2]":4: in function <[string "safecall Dispatcher[2]"]:4>
<in C code>: ?
<string>:"safecall Dispatcher[2]":13: in function `?'
CallbackHandler-1.0-6:91: in function `Fire'
AceEvent-3.0-4:120: in function <...s\ElvUI\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>
This is just one Error I got, for every new Mob a new error is generated.

## Questie & WoW version
Wotlk

**Comment by widxwer** [comment]
@Kahuma1 Could you disable all addons except Questie and see if the error still occurs?

**Comment by Kahuma1** [comment]
I disabled all addons. 
Now i get this LUA Error.
Message: ...face\AddOns\Questie-335\Modules\QuestieNameplate.lua:210: <unnamed>:SetParent(): Couldn't find region named 'Creature-0-4170-0-41-5472-00000F4B37'
Time: 05/29/24 17:38:46
Count: 2
Stack: [C]: in function `SetParent'
...face\AddOns\Questie-335\Modules\QuestieNameplate.lua:210: in function `GetFrame'
...face\AddOns\Questie-335\Modules\QuestieNameplate.lua:57: in function <...face\AddOns\Questie-335\Modules\QuestieNameplate.lua:27>
[string "safecall Dispatcher[2]"]:4: in function <[string "safecall Dispatcher[2]"]:4>
[C]: ?
[string "safecall Dispatcher[2]"]:13: in function `?'
...pat\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:92: in function `Fire'
...ddOns\Questie-335\Libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...ddOns\Questie-335\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: (*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "Creature-0-4170-0-41-5472-00000F4B37"

**Comment by widxwer** [comment]
@Kahuma1 Are you using a clean 3.3.5 client? I mean, no custom launchers, patches or libraries like [Awesome WotLK](https://github.com/FrostAtom/awesome_wotlk)?

**Comment by Kahuma1** [comment]
No, i use the HD client, and Atoms Awesome Wotlk

**Comment by widxwer** [comment]
@Kahuma1 Should be fixed in [87c02b1](https://github.com/widxwer/Questie/commit/87c02b1c65dec22fd0a096e8fc627db7ba3ad922).

**Comment by Kahuma1** [comment]
fixed ,thanks a lot
