### ISSUE TITLE
Tracker -Disable Quest not connected to current Zone

### ISSUE THREAD

**Issue by Kahuma1** [widxwer/Questie#6]
I really like the Tracker but if you have 25 Quest with their Zone names Titels and Questprogress in the Tracker u get easily lost.
The Feature from Questhelper where it only shows Quest which are relevant to the Zone, would help there a lot.
Dunno if its  easy to accomplish,

**Comment by widxwer** [comment]
@Kahuma1 Sorting quest objectives by 'Proximity' should be the solution, but it's bugged right now.
![image](https://github.com/widxwer/Questie/assets/114254296/faaa728c-ed79-4a0d-876e-1c23479eae9e)

**Comment by Kahuma1** [comment]
Thanks for the information.

**Comment by widxwer** [comment]
Sorting tracker quests by 'Proximity' should be fixed in [fd3b7b6](https://github.com/widxwer/Questie/commit/fd3b7b6b0f30d584c8ed04054e03b4f8d4cb7be2)
