### ISSUE TITLE
TomTom Arrow Tracking Wrong Locations

### ISSUE THREAD

**Issue by Kahuma1** [widxwer/Questie#7]
When Cntrl+Left Click a Quest you can get the TomTom Arrow to Point towards the Quest Area, like Questhelper etc.
If you do this with Questie the Arrow Points in the wrong direction and all other data is also wrong.
In the screen iam heading toward the Quest and i added it as waypoint via tomtom over the questie tracker, as seen the TomTom Arrow showes the opposite direction, no questtext etc.
![arrow tomtom](https://github.com/widxwer/Questie/assets/92261432/3459aca2-f09e-4e9f-a52c-7e4c45e06e4f)

**Comment by widxwer** [comment]
Fixed in [fd3b7b6](https://github.com/widxwer/Questie/commit/fd3b7b6b0f30d584c8ed04054e03b4f8d4cb7be2)

**Comment by Kahuma1** [comment]
Found another Error, you should be able to Cntrl-Leftclick on the Map objectives to get a waypoint.,thats also not possible atm even with the new version fb3b7b6.

**Comment by Kahuma1** [comment]
1x Questie-335-9.5.1\Modules\FramePool\QuestieFrame.lua:215: attempt to index local 'waypoint' (a number value)

Locals:

  ---

**Comment by Kahuma1** [comment]
> Found another Error, you should be able to Cntrl-Leftclick on the Map objectives to get a waypoint.,thats also not possible atm even with the new version fb3b7b6.

1x Questie-335-9.5.1\Modules\FramePool\QuestieFrame.lua:215: attempt to index local 'waypoint' (a number value)

Locals:

  ---

**Comment by widxwer** [comment]
@Kahuma1 should be fixed in [bcc4f0e](https://github.com/widxwer/Questie/commit/bcc4f0e1a420a406b2ae0589f4d1a5c62efe3ba4)
