### ISSUE TITLE
Quest DB Reset when changing continents

### ISSUE THREAD

**Issue by dillyns** [widxwer/Questie#8]
## Bug description

I have completed quests in 1-60 vanilla zones.
Whenever I go to Dalaran and then back to vanilla zones, the completed quests are all reset and appear on my map again as available to accept.
It is fixed by recompiling the questie DB, but this has to be done everytime.

**Comment by widxwer** [comment]
@dillyns should be fixed in [bef739e](https://github.com/widxwer/Questie/commit/bef739e227905ccb08bd75bb30839eaf02c655f7)

**Comment by dillyns** [comment]
@widxwer Looks like that fixed it
